import type { Metadata } from "next";
import { notoSansKR, roboto } from "./font";
import "../styles/globals.scss";
import "../styles/zIndex.scss";
import "../styles/reset.scss";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "CDG Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKR.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
